[tool.poetry]
name = "ce-demo"
version = "0.1.0"
description = "demo app for campus evolve"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
fastapi = ">=0.103.2"
uvicorn = ">=0.23.2"
gunicorn = "^21.2.0"
openai = ">=0.28.1"
langchain = ">=0.0.354"
python-dotenv = ">=1.0.0"
annotated-types = "0.6.0"
anyio = "3.7.1"
click = "8.1.7"
h11 = "0.14.0"
idna = "3.4"
iniconfig = "2.0.0"
packaging = "23.2"
pluggy = "1.3.0"
pydantic = "2.4.2"
pydantic-core = "2.10.1"
pydantic-settings = "2.0.3"
pytest = "7.4.2"
sniffio = "1.3.0"
starlette = "0.27.0"
typing-extensions = "4.8.0"
tiktoken = "^0.5.1"
mongoengine = "0.27.0"
azure-search-documents = "11.4.0"
azure-storage-blob = "12.18.3"
sse-starlette = "1.6.5"
azure-identity = "^1.15.0"
trulens-eval = "^0.20.2"
langchain-openai = "^0.0.2"
langchain-community = "^0.0.11"
litellm = "^1.17.3"
boto3 = "^1.34.18"
gensim = "^4.3.2"
nltk = "^3.8.1"
scikit-learn = "^1.3.2"
sklearn-features = "^0.0.2"
spacy = "^3.7.2"
torch = "^2.1.2"
unidecode = "^1.3.8"
matplotlib = "^3.8.2"
joblib = "^1.3.2"
seaborn = "^0.13.1"
langchain-core = "^0.1.15"
msal = "^1.26.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
